# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-alpine

# Install runtime and build dependencies
RUN apk add --no-cache file build-base libffi-dev openssl-dev

WORKDIR /app

# Copy project files
COPY pyproject.toml .
COPY src ./src
COPY LICENSE README.md ./

# Install package
RUN pip install --no-cache-dir .

# Set default command
CMD ["file-convert-mcp"]
